// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/download": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/download";
  };
  "pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "pages/download.tsx": {
    id: "pages/download";
    page: "/download";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/home": typeof import("./app/pages/home.tsx");
  "pages/download": typeof import("./app/pages/download.tsx");
};